---
- name: Ensure Base Command & Control Tools are Installed
  dnf:
    name:
      - zsh
      - git
      - neovim
      - zellij
      - eza
      - bat
      - fzf
      - ripgrep
    state: present

- name: Ensure 'Titan_Vault' Directory Exists
  file:
    path: "{{ ansible_env.HOME }}/TITAN_VAULT"
    state: directory
    mode: '0700'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
