version: "3.8"

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - vault_net
    labels:
      - "traefik.enable=true"
      # ROUTING: Listen on HTTPS (websecure)
      - "traefik.http.routers.grafana.rule=Host(`grafana.vault.local`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      # PORT FIX: Direct to Grafana Internal Port 3000
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      # MIDDLEWARE: Security Gate
      - "traefik.http.middlewares.auth.basicauth.users=user:$$2y$$05$$K2m16C6q92Xmawg25UcgxuG9blKHGk954kl5sOpVaoNDReCj5nhXm"
      - "traefik.http.routers.grafana.middlewares=auth"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
    networks:
      - vault_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.vault.local`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.http.routers.prometheus.middlewares=auth"

volumes:
  grafana_data:
  prometheus_data:

networks:
  vault_net:
    external: true
